# Generated by Django 5.2.3 on 2025-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
