# Generated by Django 5.2.3 on 2025-07-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_alter_tutor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='sent_request',
            field=models.BooleanField(default=False),
        ),
    ]
