# Generated by Django 5.2.3 on 2025-08-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_tutor_sent_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='preferred_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
