# Generated by Django 5.2.3 on 2025-08-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0007_alter_studentrequest_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrequest',
            name='accepted',
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
